#  Speaker

#  led   GPIO14   bl

#  LRC   GPIO11   pk
#  BLC   GPIO9    ye
#  Dout  GPIO7    vi

substitutions:

  name: your-name
  friendly_name: Your Name 
  i2s_lrclk: GPIO11
  i2s_bclk: GPIO09
  spk: GPIO07
  ledpin: GPIO48   #14
  ota_password: "stuff"
  key_encryption: "stuff"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ssid_2: !secret wifi_ssid_another
  wifi_password_2: !secret wifi_password_another
  red: 100%
  green: 0%
  blue: 0% 
  rgb: GRB
  chip: WS2812  #WS2812 / APA106
  psram: octal
  task: false
  bufdur: 100ms
  bufsize: 2000000

  task: false
  bufdur: 100ms
  bufsize: 500000

wifi:
  networks:
  - ssid: ${wifi_ssid}
    password: ${wifi_password}
  - ssid: ${wifi_ssid_2}
    password: ${wifi_password_2}

network:
  enable_high_performance: true

 # manual_ip:
 #   static_ip: ${ipaddress}
 #   gateway: 192.168.1.254
 #   subnet: 255.255.255.0

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-s3-devkitc-1
  cpu_frequency: 240MHz
  variant: esp32s3
  flash_size: ${flash}
  framework:
    type: esp-idf
    version: recommended

    sdkconfig_options:
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"
  #    CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"

# Enable logging
logger:
 # level: DEBUG
#  logs:
 #   sensor: WARN  # avoids logging debug sensor updates

# Enable Home Assistant API
api:
  encryption:
    key: ${key_encryption}

ota:
  - platform: esphome
    password: ${ota_password}
  - platform: web_server

web_server:
  port: 80

psram:
  mode: ${psram}
  speed: 80MHz

external_components:
  - source: github://pr#12284
    components: [generic_image, mdns, sendspin]
    refresh: 1h
  - source: github://pr#12253
    components: [ mixer ]
  - source: github://pr#12254
    components: [ resampler ]
  - source: github://pr#12256
    components: [ audio ]
  - source: github://pr#12258
    components: [ media_player ]
  - source: github://pr#10212
    components: [runtime_image, online_image]
    refresh: 0s
  - source: github://pr#12429
    components: [media_source, http_request, speaker_source]
    refresh: 0s

globals:
  - id: current_volume
    type: float
    initial_value: '0.2'
  - id: announcement_triggered
    type: bool
    initial_value: 'false'

sendspin:
  id: sendspin_hub
  task_stack_in_psram: ${task}
 # kalman_process_error: 0.01

i2s_audio:
  - id: i2s_output
    i2s_lrclk_pin: 
      number: ${i2s_lrclk}
    i2s_bclk_pin:  
      number: ${i2s_bclk}

speaker:
  - platform: i2s_audio
    id: i2s_audio_speaker
    sample_rate: 48000
 #   i2s_mode: secondary
    i2s_dout_pin:   
      number: ${spk}
    bits_per_sample: 32bit
 #   i2s_audio_id: i2s_output
    dac_type: external
    channel: stereo
    timeout: never
    buffer_duration: ${bufdur}

 # Virtual speakers to combine the announcement and media streams together into one output
  - platform: mixer
    id: mixing_speaker
    output_speaker: i2s_audio_speaker
    num_channels: 2
    task_stack_in_psram: ${task}
    source_speakers:
      - id: announcement_mixing_input
        timeout: never
      - id: media_mixing_input
        timeout: never

  # Vritual speakers to resample each pipelines' audio, if necessary, as the mixer speaker requires the same sample rate
  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 48000
    bits_per_sample: 16
  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

media_source:
  - platform: sendspin
    id: sendspin_source
  - platform: http_request
    id: http_source
    buffer_size: ${bufsize}
 # - platform: file
 #   id: file_source

media_player:
  - platform: sendspin
    id: player
    name: Group Player
  - platform: speaker_source
    id: external_media_player
    name: Player
    internal: False
    announcement_speaker: announcement_resampling_speaker
    media_speaker: media_resampling_speaker
    volume_increment: 0.05
    volume_min: ${volmin}
    volume_max: ${volmax}
    sources:
     # - file_source
      - http_source
      - sendspin_source

    announcement_pipeline:
      format: FLAC     # FLAC is the least processor intensive codec
      num_channels: 1  # Stereo audio is unnecessary for announcements
      sample_rate: 48000
    media_pipeline:
      format: FLAC     # FLAC is the least processor intensive codec
      num_channels: 2
      sample_rate: 48000

    on_play:               
        then:
        - light.turn_on:
            brightness: 100%
            red: ${red}
            green: ${green}
            blue: ${blue}
            id: led
            effect: none

    on_idle:              
        then:
        - light.turn_off:
            id: led   

    on_announcement:
        then:
        - light.turn_on:
            brightness: 100%
            red: ${reda}
            green: ${greena}
            blue: ${bluea}
            id: led
            effect: fast pulse
        - mixer_speaker.apply_ducking:
            id: media_mixing_input
            decibel_reduction: 20
            duration: 0.0s


    on_state:
      if:
        condition:
          and:
            - lambda: return (!id(announcement_triggered));
            - not:
                media_player.is_announcing: external_media_player
        then:
          - mixer_speaker.apply_ducking:
              id: media_mixing_input
              decibel_reduction: 0
              duration: 1.0s
 

switch:
  - platform: restart
    name: Reboot
    id: reboot_media_player_lab_reboot

sensor:
  - platform: wifi_signal
    name: WiFi
    update_interval: 60s 

light:
  - platform: esp32_rmt_led_strip
    rgb_order: ${rgb}
    pin: ${ledpin}
    num_leds: 4
    chipset: WS2812
    name: LED
    id: led
    disabled_by_default: false
    #entity_category: diagnostic
    icon: mdi:led-on
    default_transition_length: 0s
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 150ms
          update_interval: 150ms
          min_brightness: 20%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 150ms
          update_interval: 150ms
          min_brightness: 20%
          max_brightness: 100%

http_request:

text_sensor:
- platform: wifi_info
 # ip_address:
#    name: Device IP Address
#    address_0:
#      name: Device IP Address 0
  ssid:
    name: Device Connected SSID
 # bssid:
 #   name: Device Connected BSSID
 # mac_address:
 #   name: Device Mac Wifi Address
  scan_results:
    name: Device Latest Scan Results
#  dns_address:
 #   name: Device DNS Address
  power_save_mode:
    name: Device Wifi Power Save Mode


